// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTH-_p2uAbi7ucSsu3-IGn17CDm4_ylUg',
    appId: '1:1074243032575:android:70813a9cd790d438fc43ca',
    messagingSenderId: '1074243032575',
    projectId: 'rocketio',
    storageBucket: 'rocketio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAia5DYpXyLilNlqmuFaIskOg_owkRkZmE',
    appId: '1:1074243032575:ios:7e0351c2f9f5e8d1fc43ca',
    messagingSenderId: '1074243032575',
    projectId: 'rocketio',
    storageBucket: 'rocketio.appspot.com',
    iosClientId: '1074243032575-iaojcnffiqvd02r7c1287fuoc6dpehne.apps.googleusercontent.com',
    iosBundleId: 'itayoved.com',
  );
}
